### ISSUE TITLE
Configure autoplay speed

### ISSUE THREAD

**Issue by witschko** [dynamic/silverstripe-elemental-flexslider#15]
Is it possible to configure the autoplay speed via the backend?

**Comment by mak001** [comment]
To modify the speed you would need to add an extension to `Dynamic\Elements\Flexslider\Elements\ElementSlideshow` with the method `setFlexSliderSpeed()`.
`setFlexSliderSpeed()` should return an integer for the number of milliseconds a slide should show for.

This would make each slide show for 1 second, or 1000 milliseconds.
```php
public function setFlexSliderSpeed()
{
    return 1000;
}
```

You could also make a pr to add the method to `Dynamic\Elements\Flexslider\Elements\ElementSlideshow` and make it configurable with a field in the cms. I would poke around https://github.com/dynamic/silverstripe-flexslider/blob/master/src/ORM/FlexSlider.php#L105-L120 to add it to the rest of the slides tab

**Comment by muskie9** [comment]
closing in favor of https://github.com/dynamic/silverstripe-flexslider/pull/161
